import { useEffect, useState } from "react";
import Head from "next/head";
import {
  Box,
  Button,
  Flex,
  Grid,
  GridItem,
  Highlight,
  Text,
} from "@chakra-ui/react";
import { loginWithGitHub, sessionChange } from "../firebase/Client";
import { useRouter } from "next/router";
import Slider from "react-slick";
import { Logo } from "../components/Icons";

export default function Home() {
  const [dev, setDev] = useState(undefined);
  const router = useRouter();

  useEffect(() => {
    sessionChange(setDev);
  }, []);

  useEffect(() => {
    dev && router.replace("/Home");
  }, [dev]);

  const handleClick = () => {
    loginWithGitHub().catch((error) => {
      console.log(error);
    });
  };
  return (
    <>
      <Head>
        <title>Codeparty</title>
        <meta
          name="Social media for devs"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid templateColumns="repeat(3, 1fr)" gap={5} p={5} mt="30px">
        <GridItem
          layerStyle="loginBox"
          alignSelf="center"
          justifySelf="center"
        ></GridItem>
        <GridItem
          layerStyle="loginBox"
          alignSelf="center"
          justifySelf="center"
        ></GridItem>
        <GridItem
          layerStyle="loginBox"
          alignSelf="center"
          justifySelf="center"
        ></GridItem>
        <GridItem
          layerStyle="loginBox"
          alignSelf="center"
          justifySelf="center"
        ></GridItem>
        <GridItem layerStyle="loginBox" alignSelf="center" justifySelf="center">
          <Logo />
        </GridItem>
        <GridItem
          layerStyle="loginBox"
          alignSelf="center"
          justifySelf="center"
        ></GridItem>
        <GridItem
          layerStyle="loginBox"
          alignSelf="center"
          justifySelf="center"
        ></GridItem>
        <GridItem
          layerStyle="loginBox"
          alignSelf="center"
          justifySelf="center"
        ></GridItem>
        <GridItem
          layerStyle="loginBox"
          alignSelf="center"
          justifySelf="center"
        ></GridItem>
      </Grid>
      <Box
        display="flex"
        flexDirection="column"
        justifyContent="center"
        alignContent="center"
        alignItems="center"
        textAlign="center"
      >
        <Text
          textAlign="center"
          fontWeight={800}
          fontSize="30px"
          w="250px"
          mt="40px"
        >
          Find New Devs With
          <span style={{ color: "#159BFF", marginLeft: "6px" }}>Codeparty</span>
        </Text>
        <Text
          textAlign="center"
          fontWeight={400}
          fontSize="15px"
          w="200px"
          mt="15px"
          color="gray"
        >
          Talk and share with others developers around the world
        </Text>
        <Button variant="primary" onClick={handleClick} mt="50px">
          Iniciar sesion con Github
        </Button>
      </Box>
    </>
  );
}
