import { useEffect, useState } from "react";
import Head from "next/head";
import { Button, Text } from "@chakra-ui/react";
import { loginWithGitHub, sessionChange } from "../firebase/firebaseConfig";
import { useRouter } from "next/router";

export default function Home() {
  const [dev, setDev] = useState(undefined);
  const router = useRouter();

  useEffect(() => {
    sessionChange(setDev);
  }, []);

  useEffect(() => {
    dev && router.replace("/Home");
  }, [dev]);

  const handleClick = () => {
    loginWithGitHub().catch((error) => {
      console.log(error);
    });
  };
  return (
    <>
      <Head>
        <title>Codeparty</title>
        <meta
          name="Social media for devs"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Text>hola que tal</Text>
      <Button onClick={handleClick}>Iniciar sesion con Github</Button>
    </>
  );
}
