import { useEffect, useState } from "react";
import Head from "next/head";
import { Box, Button, Flex, Grid, GridItem, Text } from "@chakra-ui/react";
import { loginWithGitHub, sessionChange } from "../firebase/firebaseConfig";
import { useRouter } from "next/router";
import Slider from "react-slick";

export default function Home() {
  const [dev, setDev] = useState(undefined);
  const router = useRouter();

  useEffect(() => {
    sessionChange(setDev);
  }, []);

  useEffect(() => {
    dev && router.replace("/Home");
  }, [dev]);

  const handleClick = () => {
    loginWithGitHub().catch((error) => {
      console.log(error);
    });
  };
  return (
    <>
      <Head>
        <title>Codeparty</title>
        <meta
          name="Social media for devs"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid templateColumns="repeat(3, 1fr)" gap={5} p={5}>
        <GridItem
          layerStyle="stories"
          alignSelf="center"
          justifySelf="center"
        ></GridItem>
        <GridItem
          layerStyle="stories"
          alignSelf="center"
          justifySelf="center"
        ></GridItem>
        <GridItem
          layerStyle="stories"
          alignSelf="center"
          justifySelf="center"
        ></GridItem>
        <GridItem
          layerStyle="stories"
          alignSelf="center"
          justifySelf="center"
        ></GridItem>
        <GridItem
          layerStyle="stories"
          alignSelf="center"
          justifySelf="center"
        ></GridItem>
        <GridItem
          layerStyle="stories"
          alignSelf="center"
          justifySelf="center"
        ></GridItem>
        <GridItem
          layerStyle="stories"
          alignSelf="center"
          justifySelf="center"
        ></GridItem>
        <GridItem
          layerStyle="stories"
          alignSelf="center"
          justifySelf="center"
        ></GridItem>
        <GridItem
          layerStyle="stories"
          alignSelf="center"
          justifySelf="center"
        ></GridItem>
      </Grid>
      <Box
        display="flex"
        flexDirection="column"
        justifyContent="center"
        alignContent="center"
        alignItems="center"
        textAlign="center"
      >
        <Text textAlign="center" fontWeight={800} fontSize="30px" w="250px">
          Find New Devs With Codeparty
        </Text>
        <Text textAlign="center" fontSize="15px" w="200px">
          Talk and share with others developers around the world
        </Text>
        <Button onClick={handleClick}>Iniciar sesion con Github</Button>
      </Box>
    </>
  );
}
